//! `hooks-build bindings-ts` — generates a small, dependency-free
//! TypeScript module from a `spec.json` (`crate::spec`), for consumption by
//! `@transia/hooks-toolkit`-based e2e tests (`docs/SPEC-SIDECAR.md`).
//!
//! The generated module replaces hand-written hex in test code
//! (`convertStringToHex('BL')`, manually zero-padded state keys, …) with
//! named constants and a couple of small builder functions, all derived
//! mechanically from the same `hook-spec.toml` that documents the hook's
//! interface. Nothing here is hooks-toolkit-specific beyond the
//! `HookParameters` array shape (`{ HookParameter: { HookParameterName,
//! HookParameterValue } }`), which is the `SetHook` transaction's own wire
//! shape, not a toolkit convention.
//!
//! This module intentionally emits plain strings rather than using a
//! templating engine or code-gen crate — the output is small, fully
//! specified below, and a plain-string generator is trivially reviewable
//! byte-for-byte (mirrors the "no walrus" philosophy elsewhere in this
//! crate, `docs/DESIGN.md` §6).

use std::fmt::Write as _;

use crate::spec::{HookSpec, KeyDerivation};

/// Generates the TypeScript module source for `spec`.
///
/// - Hook parameters become a `HOOK_PARAM_NAMES` map (hex-encoded,
///   uppercase, no `0x` prefix — matching `convertStringToHex`/
///   `accountIdHex`'s existing hand-written convention in `e2e/test/`), a
///   parallel `HOOK_PARAM_BYTES` length map, a value-bag type, and a
///   `build<PascalName>HookParameters` function that validates each
///   value's byte length and assembles the `HookParameters` array a
///   `SetHook` transaction expects.
/// - Hook-state entries become a `HOOK_STATE_KEYS` map of pre-computed,
///   32-byte, hex-encoded state keys (ASCII-padded keys are folded to hex
///   here, at generation time — the consumer never needs to reimplement
///   `pad!`).
/// - Build facts (`wasm_file`, `size_bytes`, `sha256`, `hook_api_version`,
///   `hook_cost`, `cbak_cost`, `sdk_version`) become a `HOOK_BUILD` constant,
///   and `transaction_types` becomes `HOOK_TRANSACTION_TYPES`.
///
/// Sections whose backing data is empty (no `hook-spec.toml`, or one that
/// declared no params/state/transaction types) are omitted from the output
/// entirely rather than emitted as empty/misleading constants.
#[must_use]
pub fn generate_ts(spec: &HookSpec) -> String {
    let name = spec
        .hook
        .as_ref()
        .map(|h| h.name.clone())
        .unwrap_or_else(|| stem(&spec.build.wasm_file));
    let pascal = pascal_case(&name);

    let mut out = String::new();
    let _ = writeln!(
        out,
        "// AUTO-GENERATED by `hooks-build bindings-ts` — do not edit by hand."
    );
    let _ = writeln!(
        out,
        "// Source: {}'s spec.json (spec_version {}).",
        spec.build.wasm_file, spec.spec_version
    );
    if let Some(hook) = &spec.hook
        && !hook.description.is_empty()
    {
        let _ = writeln!(out, "//");
        let _ = writeln!(out, "// {}: {}", hook.name, hook.description);
    }
    let _ = writeln!(out);

    if !spec.params.is_empty() {
        emit_params(&mut out, &pascal, &spec.params);
    }

    if !spec.state.is_empty() {
        emit_state(&mut out, &spec.state);
    }

    if !spec.transaction_types.is_empty() {
        let list = spec
            .transaction_types
            .iter()
            .map(|t| format!("'{t}'"))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(
            out,
            "/** `TransactionType`s this hook expects to be invoked for. */"
        );
        let _ = writeln!(
            out,
            "export const HOOK_TRANSACTION_TYPES = [{list}] as const"
        );
        let _ = writeln!(out);
    }

    let _ = writeln!(out, "/** `HookApiVersion` this module targets. */");
    let _ = writeln!(
        out,
        "export const HOOK_API_VERSION = {} as const",
        spec.build.hook_api_version
    );
    let _ = writeln!(out);

    let _ = writeln!(
        out,
        "/** Build facts recorded by `hooks-build` for this artifact. */"
    );
    let _ = writeln!(out, "export const HOOK_BUILD = {{");
    let _ = writeln!(out, "  wasmFile: '{}',", spec.build.wasm_file);
    let _ = writeln!(out, "  sizeBytes: {},", spec.build.size_bytes);
    let _ = writeln!(out, "  sha256: '{}',", spec.build.sha256);
    let _ = writeln!(out, "  hookApiVersion: {},", spec.build.hook_api_version);
    match spec.build.hook_cost {
        Some(cost) => {
            let _ = writeln!(out, "  hookCost: {cost},");
        }
        None => {
            let _ = writeln!(out, "  hookCost: null as number | null,");
        }
    }
    match spec.build.cbak_cost {
        Some(cost) => {
            let _ = writeln!(out, "  cbakCost: {cost},");
        }
        None => {
            let _ = writeln!(out, "  cbakCost: null as number | null,");
        }
    }
    let _ = writeln!(out, "  sdkVersion: '{}',", spec.build.sdk_version);
    let _ = writeln!(out, "}} as const");

    out
}

/// One `HookParameters` entry, the `SetHook` wire shape.
const SET_HOOK_PARAMETER_ENTRY_TYPE: &str = "export interface SetHookParameterEntry {
  HookParameter: {
    HookParameterName: string
    HookParameterValue: string
  }
}";

fn emit_params(out: &mut String, pascal: &str, params: &[crate::spec::ParamSpec]) {
    let _ = writeln!(
        out,
        "/** Hex-encoded `HookParameterName` values (uppercase, no `0x` prefix). */"
    );
    let _ = writeln!(out, "export const HOOK_PARAM_NAMES = {{");
    for p in params {
        let _ = writeln!(
            out,
            "  {}: '{}',",
            p.name,
            hex_encode_upper(p.name.as_bytes())
        );
    }
    let _ = writeln!(out, "}} as const");
    let _ = writeln!(out);

    let _ = writeln!(
        out,
        "/** Expected `HookParameterValue` byte length for each parameter. */"
    );
    let _ = writeln!(out, "export const HOOK_PARAM_BYTES = {{");
    for p in params {
        let _ = writeln!(out, "  {}: {},", p.name, p.bytes);
    }
    let _ = writeln!(out, "}} as const");
    let _ = writeln!(out);

    let _ = writeln!(
        out,
        "/** Hex-encoded `HookParameterValue`s, keyed by parameter name. */"
    );
    let _ = writeln!(out, "export interface {pascal}HookParameterValues {{");
    for p in params {
        if p.description.is_empty() {
            let _ = writeln!(out, "  /** {} bytes, hex-encoded. */", p.bytes);
        } else {
            let _ = writeln!(
                out,
                "  /** {} ({} bytes, hex-encoded.) */",
                p.description, p.bytes
            );
        }
        let _ = writeln!(out, "  {}: string", p.name);
    }
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);

    let _ = writeln!(out, "{SET_HOOK_PARAMETER_ENTRY_TYPE}");
    let _ = writeln!(out);

    let _ = writeln!(
        out,
        "/**\n * Builds the `HookParameters` array for a `SetHook` transaction installing\n * `{pascal}`. Throws if a value's decoded byte length does not match the\n * spec.\n */"
    );
    let _ = writeln!(
        out,
        "export function build{pascal}HookParameters(values: {pascal}HookParameterValues): SetHookParameterEntry[] {{"
    );
    let _ = writeln!(out, "  const entries: SetHookParameterEntry[] = []");
    for p in params {
        let _ = writeln!(out, "  {{");
        let _ = writeln!(out, "    const value = values.{}", p.name);
        let _ = writeln!(
            out,
            "    const decodedLen = Buffer.from(value, 'hex').length"
        );
        let _ = writeln!(
            out,
            "    if (decodedLen !== HOOK_PARAM_BYTES.{}) {{",
            p.name
        );
        let _ = writeln!(
            out,
            "      throw new Error(`{pascal}: HookParameter '{}' must be ${{HOOK_PARAM_BYTES.{}}} bytes, got ${{decodedLen}}`)",
            p.name, p.name
        );
        let _ = writeln!(out, "    }}");
        let _ = writeln!(out, "    entries.push({{");
        let _ = writeln!(out, "      HookParameter: {{");
        let _ = writeln!(
            out,
            "        HookParameterName: HOOK_PARAM_NAMES.{},",
            p.name
        );
        let _ = writeln!(out, "        HookParameterValue: value.toUpperCase(),");
        let _ = writeln!(out, "      }},");
        let _ = writeln!(out, "    }})");
        let _ = writeln!(out, "  }}");
    }
    let _ = writeln!(out, "  return entries");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
}

fn emit_state(out: &mut String, state: &[crate::spec::StateKeySpec]) {
    let _ = writeln!(
        out,
        "/** Pre-computed 32-byte hook-state keys, hex-encoded (uppercase). */"
    );
    let _ = writeln!(out, "export const HOOK_STATE_KEYS = {{");
    for s in state {
        let key_hex = match s.key_derivation {
            KeyDerivation::AsciiPadded => {
                let mut bytes = s.key.as_bytes().to_vec();
                bytes.resize(32, 0);
                hex_encode_upper(&bytes)
            }
            KeyDerivation::Hex => s.key.to_uppercase(),
        };
        if !s.description.is_empty() {
            let _ = writeln!(out, "  // {}: {}", s.key_name, s.description);
        }
        let _ = writeln!(out, "  {}: '{}',", s.key_name, key_hex);
    }
    let _ = writeln!(out, "}} as const");
    let _ = writeln!(out);
}

/// Uppercase hex encoding, no `0x` prefix — matches the convention already
/// used by hand-written hex in `e2e/test/` (`convertStringToHex`,
/// `.toString('hex').toUpperCase()`).
fn hex_encode_upper(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len().saturating_mul(2));
    for b in bytes {
        let _ = write!(s, "{b:02X}");
    }
    s
}

/// PascalCase a hook/crate name (`state-counter` -> `StateCounter`,
/// `emit_txn` -> `EmitTxn`) for use as a TypeScript type/function name
/// fragment. Non-alphanumeric characters are treated as word separators.
fn pascal_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut capitalize_next = true;
    for c in name.chars() {
        if c.is_alphanumeric() {
            if capitalize_next {
                out.extend(c.to_uppercase());
            } else {
                out.push(c);
            }
            capitalize_next = false;
        } else {
            capitalize_next = true;
        }
    }
    if out.is_empty() {
        "Hook".to_string()
    } else {
        out
    }
}

/// The file stem of a wasm file name (`firewall.wasm` -> `firewall`), used
/// as a fallback hook name when no `hook-spec.toml` was found.
fn stem(wasm_file: &str) -> String {
    wasm_file
        .strip_suffix(".wasm")
        .unwrap_or(wasm_file)
        .to_string()
}

#[cfg(test)]
mod tests {
    #![allow(
        clippy::unwrap_used,
        clippy::expect_used,
        clippy::panic,
        clippy::indexing_slicing
    )]

    use super::*;
    use crate::spec::{BuildInfo, HookMeta, InvokeSpec, ParamSpec, StateKeySpec, merge};

    fn sample_spec() -> HookSpec {
        let input = crate::spec::HookSpecInput {
            hook: HookMeta {
                name: "firewall".to_string(),
                description: "Rolls back transactions from a blacklisted sender.".to_string(),
            },
            params: vec![ParamSpec {
                name: "BL".to_string(),
                bytes: 20,
                description: "20-byte blocked AccountId.".to_string(),
            }],
            state: vec![StateKeySpec {
                key_name: "counter".to_string(),
                key_derivation: KeyDerivation::AsciiPadded,
                key: "counter".to_string(),
                value_type: "u64".to_string(),
                value_bytes: 8,
                description: "Monotonic invocation counter.".to_string(),
            }],
            transaction_types: vec!["Payment".to_string()],
            invoke: Some(InvokeSpec {
                hook_on: Some("Payment".to_string()),
                notes: None,
            }),
        };
        let build = BuildInfo {
            wasm_file: "firewall.wasm".to_string(),
            size_bytes: 1234,
            sha256: "0".repeat(64),
            hook_api_version: 0,
            hook_cost: Some(714),
            cbak_cost: Some(0),
            sdk_version: "0.1.0".to_string(),
        };
        merge(Some(input), build)
    }

    /// Snapshot test against a checked-in fixture — any change to the
    /// generated TypeScript shape must be a deliberate, reviewed edit.
    #[test]
    fn matches_snapshot() {
        let ts = generate_ts(&sample_spec());
        let expected = include_str!("../tests/fixtures/firewall.generated.ts");
        assert_eq!(ts.trim_end(), expected.trim_end());
    }

    #[test]
    fn minimal_spec_omits_empty_sections() {
        let build = BuildInfo {
            wasm_file: "accept_all.wasm".to_string(),
            size_bytes: 100,
            sha256: "1".repeat(64),
            hook_api_version: 0,
            hook_cost: Some(10),
            cbak_cost: Some(0),
            sdk_version: "0.1.0".to_string(),
        };
        let spec = merge(None, build);
        let ts = generate_ts(&spec);
        assert!(!ts.contains("HOOK_PARAM_NAMES"));
        assert!(!ts.contains("HOOK_STATE_KEYS"));
        assert!(!ts.contains("HOOK_TRANSACTION_TYPES"));
        assert!(ts.contains("HOOK_BUILD"));
    }

    #[test]
    fn pascal_case_handles_separators() {
        assert_eq!(pascal_case("state-counter"), "StateCounter");
        assert_eq!(pascal_case("emit_txn"), "EmitTxn");
        assert_eq!(pascal_case("firewall"), "Firewall");
    }
}
