// AUTO-GENERATED by `hooks-build bindings-ts` — do not edit by hand.
// Source: firewall.wasm's spec.json (spec_version 1).
//
// firewall: Rolls back transactions from a blacklisted sender.

/** Hex-encoded `HookParameterName` values (uppercase, no `0x` prefix). */
export const HOOK_PARAM_NAMES = {
  BL: '424C',
} as const

/** Expected `HookParameterValue` byte length for each parameter. */
export const HOOK_PARAM_BYTES = {
  BL: 20,
} as const

/** Hex-encoded `HookParameterValue`s, keyed by parameter name. */
export interface FirewallHookParameterValues {
  /** 20-byte blocked AccountId. (20 bytes, hex-encoded.) */
  BL: string
}

export interface SetHookParameterEntry {
  HookParameter: {
    HookParameterName: string
    HookParameterValue: string
  }
}

/**
 * Builds the `HookParameters` array for a `SetHook` transaction installing
 * `Firewall`. Throws if a value's decoded byte length does not match the
 * spec.
 */
export function buildFirewallHookParameters(values: FirewallHookParameterValues): SetHookParameterEntry[] {
  const entries: SetHookParameterEntry[] = []
  {
    const value = values.BL
    const decodedLen = Buffer.from(value, 'hex').length
    if (decodedLen !== HOOK_PARAM_BYTES.BL) {
      throw new Error(`Firewall: HookParameter 'BL' must be ${HOOK_PARAM_BYTES.BL} bytes, got ${decodedLen}`)
    }
    entries.push({
      HookParameter: {
        HookParameterName: HOOK_PARAM_NAMES.BL,
        HookParameterValue: value.toUpperCase(),
      },
    })
  }
  return entries
}

/** Pre-computed 32-byte hook-state keys, hex-encoded (uppercase). */
export const HOOK_STATE_KEYS = {
  // counter: Monotonic invocation counter.
  counter: '636F756E74657200000000000000000000000000000000000000000000000000',
} as const

/** `TransactionType`s this hook expects to be invoked for. */
export const HOOK_TRANSACTION_TYPES = ['Payment'] as const

/** `HookApiVersion` this module targets. */
export const HOOK_API_VERSION = 0 as const

/** Build facts recorded by `hooks-build` for this artifact. */
export const HOOK_BUILD = {
  wasmFile: 'firewall.wasm',
  sizeBytes: 1234,
  sha256: '0000000000000000000000000000000000000000000000000000000000000000',
  hookApiVersion: 0,
  hookCost: 714,
  cbakCost: 0,
  sdkVersion: '0.1.0',
} as const
