//! Per-file generators: each submodule turns one or two parsed vendored
//! headers into the exact `crates/hooks-core/src/*.rs` file content
//! described by `docs/DESIGN.md` §4.

/// Generates `crates/hooks-core/src/api.rs` from `extern.h`.
pub mod api;
/// Generates `crates/hooks-core/src/consts.rs` from `hookapi.h`/`macro.h`.
pub mod consts;
/// Generates `crates/hooks-core/src/error.rs` from `error.h`.
pub mod error;
/// Generates `crates/hooks-core/src/host.rs`: the `HookHost` trait + `Guest`.
pub mod host;
/// Generates `crates/hooks-core/src/ls_flags.rs` from `ls_flags.h`.
pub mod ls_flags;
/// Generates `crates/hooks-core/src/sfcodes.rs` from `sfcodes.h`.
pub mod sfcodes;
/// Generates `crates/hooks-core/src/tts.rs` from `tts.h`.
pub mod tts;
/// Generates `crates/hooks-core/src/tx_flags.rs` from `tx_flags.h`.
pub mod tx_flags;

/// Prepends the required `// @generated ...` marker to a module's `//!`
/// doc-comment body, per `docs/DESIGN.md` §4 / the xtask spec: every
/// generated file starts with this marker, followed immediately by its
/// module-level docs.
pub fn with_generated_marker(inputs: &str, module_doc: &str) -> String {
    format!(
        "// @generated by `cargo xtask gen-core` from crates/hooks-core/vendor/xahaud-hook/{inputs} — DO NOT EDIT BY HAND.\n{module_doc}"
    )
}

/// Appends one `/// <line>` doc comment followed by `pub const NAME: TY =
/// VALUE;` to `buf`. `doc_lines` may be more than one line (used for the
/// one hand-annotated irregular value in `error.rs`).
pub fn push_const(buf: &mut String, doc_lines: &[String], name: &str, ty: &str, value: &str) {
    for line in doc_lines {
        buf.push_str("/// ");
        buf.push_str(line);
        buf.push('\n');
    }
    buf.push_str("pub const ");
    buf.push_str(name);
    buf.push_str(": ");
    buf.push_str(ty);
    buf.push_str(" = ");
    buf.push_str(value);
    buf.push_str(";\n");
}
