// @generated by `cargo xtask gen-core` from crates/hooks-core/vendor/xahaud-hook/tts.h — DO NOT EDIT BY HAND.
//! Transaction type (`TxType`) model.
//!
//! [`TxType`] is a typed, exhaustive-by-construction mirror of the raw
//! `tt*` transaction-type codes in `hooks_core::tts` (plus
//! [`TxType::Unknown`] for forward-compatibility with codes this crate
//! does not yet know about) — the same pattern [`crate::error::HookError`]
//! uses for the Hook API's negative error-code channel, applied here to
//! [`crate::api::otxn::otxn_type`]'s `u16` transaction-type channel.

/// The transaction type of the originating transaction, decoded from the
/// raw `u16` `tt*` code returned by [`crate::api::otxn::otxn_type`].
///
/// # Examples
///
/// ```
/// use hooks_lib::tx_type::TxType;
///
/// let ty = TxType::from(5);
/// assert_eq!(ty, TxType::SetRegularKey);
/// assert_eq!(ty.code(), 5);
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TxType {
    /// `ttPAYMENT` (0).
    Payment,
    /// `ttESCROW_CREATE` (1).
    EscrowCreate,
    /// `ttESCROW_FINISH` (2).
    EscrowFinish,
    /// `ttACCOUNT_SET` (3).
    AccountSet,
    /// `ttESCROW_CANCEL` (4).
    EscrowCancel,
    /// `ttREGULAR_KEY_SET` (5).
    SetRegularKey,
    /// `ttOFFER_CREATE` (7).
    OfferCreate,
    /// `ttOFFER_CANCEL` (8).
    OfferCancel,
    /// `ttTICKET_CREATE` (10).
    TicketCreate,
    /// `ttSIGNER_LIST_SET` (12).
    SignerListSet,
    /// `ttPAYCHAN_CREATE` (13).
    PaymentChannelCreate,
    /// `ttPAYCHAN_FUND` (14).
    PaymentChannelFund,
    /// `ttPAYCHAN_CLAIM` (15).
    PaymentChannelClaim,
    /// `ttCHECK_CREATE` (16).
    CheckCreate,
    /// `ttCHECK_CASH` (17).
    CheckCash,
    /// `ttCHECK_CANCEL` (18).
    CheckCancel,
    /// `ttDEPOSIT_PREAUTH` (19).
    DepositPreauth,
    /// `ttTRUST_SET` (20).
    TrustSet,
    /// `ttACCOUNT_DELETE` (21).
    AccountDelete,
    /// `ttHOOK_SET` (22).
    SetHook,
    /// `ttNFTOKEN_MINT` (25).
    NFTokenMint,
    /// `ttNFTOKEN_BURN` (26).
    NFTokenBurn,
    /// `ttNFTOKEN_CREATE_OFFER` (27).
    NFTokenCreateOffer,
    /// `ttNFTOKEN_CANCEL_OFFER` (28).
    NFTokenCancelOffer,
    /// `ttNFTOKEN_ACCEPT_OFFER` (29).
    NFTokenAcceptOffer,
    /// `ttCLAWBACK` (30).
    Clawback,
    /// `ttAMM_CLAWBACK` (31).
    AMMClawback,
    /// `ttAMM_CREATE` (35).
    AMMCreate,
    /// `ttAMM_DEPOSIT` (36).
    AMMDeposit,
    /// `ttAMM_WITHDRAW` (37).
    AMMWithdraw,
    /// `ttAMM_VOTE` (38).
    AMMVote,
    /// `ttAMM_BID` (39).
    AMMBid,
    /// `ttAMM_DELETE` (40).
    AMMDelete,
    /// `ttURITOKEN_MINT` (45).
    URITokenMint,
    /// `ttURITOKEN_BURN` (46).
    URITokenBurn,
    /// `ttURITOKEN_BUY` (47).
    URITokenBuy,
    /// `ttURITOKEN_CREATE_SELL_OFFER` (48).
    URITokenCreateSellOffer,
    /// `ttURITOKEN_CANCEL_SELL_OFFER` (49).
    URITokenCancelSellOffer,
    /// `ttXCHAIN_CREATE_CLAIM_ID` (50).
    XChainCreateClaimID,
    /// `ttXCHAIN_COMMIT` (51).
    XChainCommit,
    /// `ttXCHAIN_CLAIM` (52).
    XChainClaim,
    /// `ttXCHAIN_ACCOUNT_CREATE_COMMIT` (53).
    XChainAccountCreateCommit,
    /// `ttXCHAIN_ADD_CLAIM_ATTESTATION` (54).
    XChainAddClaimAttestation,
    /// `ttXCHAIN_ADD_ACCOUNT_CREATE_ATTESTATION` (55).
    XChainAddAccountCreateAttestation,
    /// `ttXCHAIN_MODIFY_BRIDGE` (56).
    XChainModifyBridge,
    /// `ttXCHAIN_CREATE_BRIDGE` (57).
    XChainCreateBridge,
    /// `ttDID_SET` (58).
    DIDSet,
    /// `ttDID_DELETE` (59).
    DIDDelete,
    /// `ttORACLE_SET` (60).
    OracleSet,
    /// `ttORACLE_DELETE` (61).
    OracleDelete,
    /// `ttLEDGER_STATE_FIX` (62).
    LedgerStateFix,
    /// `ttMPTOKEN_ISSUANCE_CREATE` (63).
    MPTokenIssuanceCreate,
    /// `ttMPTOKEN_ISSUANCE_DESTROY` (64).
    MPTokenIssuanceDestroy,
    /// `ttMPTOKEN_ISSUANCE_SET` (65).
    MPTokenIssuanceSet,
    /// `ttMPTOKEN_AUTHORIZE` (66).
    MPTokenAuthorize,
    /// `ttCREDENTIAL_CREATE` (67).
    CredentialCreate,
    /// `ttCREDENTIAL_ACCEPT` (68).
    CredentialAccept,
    /// `ttCREDENTIAL_DELETE` (69).
    CredentialDelete,
    /// `ttNFTOKEN_MODIFY` (70).
    NFTokenModify,
    /// `ttPERMISSIONED_DOMAIN_SET` (71).
    PermissionedDomainSet,
    /// `ttPERMISSIONED_DOMAIN_DELETE` (72).
    PermissionedDomainDelete,
    /// `ttCRON` (92).
    Cron,
    /// `ttCRON_SET` (93).
    CronSet,
    /// `ttREMARKS_SET` (94).
    SetRemarks,
    /// `ttREMIT` (95).
    Remit,
    /// `ttGENESIS_MINT` (96).
    GenesisMint,
    /// `ttIMPORT` (97).
    Import,
    /// `ttCLAIM_REWARD` (98).
    ClaimReward,
    /// `ttINVOKE` (99).
    Invoke,
    /// `ttAMENDMENT` (100).
    EnableAmendment,
    /// `ttFEE` (101).
    SetFee,
    /// `ttUNL_MODIFY` (102).
    UNLModify,
    /// `ttEMIT_FAILURE` (103).
    EmitFailure,
    /// `ttUNL_REPORT` (104).
    UNLReport,

    /// A code this version of hooks-lib does not recognize yet. Carries
    /// the raw code for forward-compatibility.
    Unknown(u16),
}

impl From<u16> for TxType {
    fn from(code: u16) -> Self {
        match code {
            hooks_core::ttPAYMENT => TxType::Payment,
            hooks_core::ttESCROW_CREATE => TxType::EscrowCreate,
            hooks_core::ttESCROW_FINISH => TxType::EscrowFinish,
            hooks_core::ttACCOUNT_SET => TxType::AccountSet,
            hooks_core::ttESCROW_CANCEL => TxType::EscrowCancel,
            hooks_core::ttREGULAR_KEY_SET => TxType::SetRegularKey,
            hooks_core::ttOFFER_CREATE => TxType::OfferCreate,
            hooks_core::ttOFFER_CANCEL => TxType::OfferCancel,
            hooks_core::ttTICKET_CREATE => TxType::TicketCreate,
            hooks_core::ttSIGNER_LIST_SET => TxType::SignerListSet,
            hooks_core::ttPAYCHAN_CREATE => TxType::PaymentChannelCreate,
            hooks_core::ttPAYCHAN_FUND => TxType::PaymentChannelFund,
            hooks_core::ttPAYCHAN_CLAIM => TxType::PaymentChannelClaim,
            hooks_core::ttCHECK_CREATE => TxType::CheckCreate,
            hooks_core::ttCHECK_CASH => TxType::CheckCash,
            hooks_core::ttCHECK_CANCEL => TxType::CheckCancel,
            hooks_core::ttDEPOSIT_PREAUTH => TxType::DepositPreauth,
            hooks_core::ttTRUST_SET => TxType::TrustSet,
            hooks_core::ttACCOUNT_DELETE => TxType::AccountDelete,
            hooks_core::ttHOOK_SET => TxType::SetHook,
            hooks_core::ttNFTOKEN_MINT => TxType::NFTokenMint,
            hooks_core::ttNFTOKEN_BURN => TxType::NFTokenBurn,
            hooks_core::ttNFTOKEN_CREATE_OFFER => TxType::NFTokenCreateOffer,
            hooks_core::ttNFTOKEN_CANCEL_OFFER => TxType::NFTokenCancelOffer,
            hooks_core::ttNFTOKEN_ACCEPT_OFFER => TxType::NFTokenAcceptOffer,
            hooks_core::ttCLAWBACK => TxType::Clawback,
            hooks_core::ttAMM_CLAWBACK => TxType::AMMClawback,
            hooks_core::ttAMM_CREATE => TxType::AMMCreate,
            hooks_core::ttAMM_DEPOSIT => TxType::AMMDeposit,
            hooks_core::ttAMM_WITHDRAW => TxType::AMMWithdraw,
            hooks_core::ttAMM_VOTE => TxType::AMMVote,
            hooks_core::ttAMM_BID => TxType::AMMBid,
            hooks_core::ttAMM_DELETE => TxType::AMMDelete,
            hooks_core::ttURITOKEN_MINT => TxType::URITokenMint,
            hooks_core::ttURITOKEN_BURN => TxType::URITokenBurn,
            hooks_core::ttURITOKEN_BUY => TxType::URITokenBuy,
            hooks_core::ttURITOKEN_CREATE_SELL_OFFER => TxType::URITokenCreateSellOffer,
            hooks_core::ttURITOKEN_CANCEL_SELL_OFFER => TxType::URITokenCancelSellOffer,
            hooks_core::ttXCHAIN_CREATE_CLAIM_ID => TxType::XChainCreateClaimID,
            hooks_core::ttXCHAIN_COMMIT => TxType::XChainCommit,
            hooks_core::ttXCHAIN_CLAIM => TxType::XChainClaim,
            hooks_core::ttXCHAIN_ACCOUNT_CREATE_COMMIT => TxType::XChainAccountCreateCommit,
            hooks_core::ttXCHAIN_ADD_CLAIM_ATTESTATION => TxType::XChainAddClaimAttestation,
            hooks_core::ttXCHAIN_ADD_ACCOUNT_CREATE_ATTESTATION => {
                TxType::XChainAddAccountCreateAttestation
            }
            hooks_core::ttXCHAIN_MODIFY_BRIDGE => TxType::XChainModifyBridge,
            hooks_core::ttXCHAIN_CREATE_BRIDGE => TxType::XChainCreateBridge,
            hooks_core::ttDID_SET => TxType::DIDSet,
            hooks_core::ttDID_DELETE => TxType::DIDDelete,
            hooks_core::ttORACLE_SET => TxType::OracleSet,
            hooks_core::ttORACLE_DELETE => TxType::OracleDelete,
            hooks_core::ttLEDGER_STATE_FIX => TxType::LedgerStateFix,
            hooks_core::ttMPTOKEN_ISSUANCE_CREATE => TxType::MPTokenIssuanceCreate,
            hooks_core::ttMPTOKEN_ISSUANCE_DESTROY => TxType::MPTokenIssuanceDestroy,
            hooks_core::ttMPTOKEN_ISSUANCE_SET => TxType::MPTokenIssuanceSet,
            hooks_core::ttMPTOKEN_AUTHORIZE => TxType::MPTokenAuthorize,
            hooks_core::ttCREDENTIAL_CREATE => TxType::CredentialCreate,
            hooks_core::ttCREDENTIAL_ACCEPT => TxType::CredentialAccept,
            hooks_core::ttCREDENTIAL_DELETE => TxType::CredentialDelete,
            hooks_core::ttNFTOKEN_MODIFY => TxType::NFTokenModify,
            hooks_core::ttPERMISSIONED_DOMAIN_SET => TxType::PermissionedDomainSet,
            hooks_core::ttPERMISSIONED_DOMAIN_DELETE => TxType::PermissionedDomainDelete,
            hooks_core::ttCRON => TxType::Cron,
            hooks_core::ttCRON_SET => TxType::CronSet,
            hooks_core::ttREMARKS_SET => TxType::SetRemarks,
            hooks_core::ttREMIT => TxType::Remit,
            hooks_core::ttGENESIS_MINT => TxType::GenesisMint,
            hooks_core::ttIMPORT => TxType::Import,
            hooks_core::ttCLAIM_REWARD => TxType::ClaimReward,
            hooks_core::ttINVOKE => TxType::Invoke,
            hooks_core::ttAMENDMENT => TxType::EnableAmendment,
            hooks_core::ttFEE => TxType::SetFee,
            hooks_core::ttUNL_MODIFY => TxType::UNLModify,
            hooks_core::ttEMIT_FAILURE => TxType::EmitFailure,
            hooks_core::ttUNL_REPORT => TxType::UNLReport,
            other => TxType::Unknown(other),
        }
    }
}

impl TxType {
    /// The raw `u16` code this variant corresponds to. Exact inverse of
    /// [`TxType::from`]: `TxType::from(c).code() == c` for every code,
    /// known or unknown.
    #[inline(always)]
    #[must_use]
    pub fn code(&self) -> u16 {
        match *self {
            TxType::Payment => hooks_core::ttPAYMENT,
            TxType::EscrowCreate => hooks_core::ttESCROW_CREATE,
            TxType::EscrowFinish => hooks_core::ttESCROW_FINISH,
            TxType::AccountSet => hooks_core::ttACCOUNT_SET,
            TxType::EscrowCancel => hooks_core::ttESCROW_CANCEL,
            TxType::SetRegularKey => hooks_core::ttREGULAR_KEY_SET,
            TxType::OfferCreate => hooks_core::ttOFFER_CREATE,
            TxType::OfferCancel => hooks_core::ttOFFER_CANCEL,
            TxType::TicketCreate => hooks_core::ttTICKET_CREATE,
            TxType::SignerListSet => hooks_core::ttSIGNER_LIST_SET,
            TxType::PaymentChannelCreate => hooks_core::ttPAYCHAN_CREATE,
            TxType::PaymentChannelFund => hooks_core::ttPAYCHAN_FUND,
            TxType::PaymentChannelClaim => hooks_core::ttPAYCHAN_CLAIM,
            TxType::CheckCreate => hooks_core::ttCHECK_CREATE,
            TxType::CheckCash => hooks_core::ttCHECK_CASH,
            TxType::CheckCancel => hooks_core::ttCHECK_CANCEL,
            TxType::DepositPreauth => hooks_core::ttDEPOSIT_PREAUTH,
            TxType::TrustSet => hooks_core::ttTRUST_SET,
            TxType::AccountDelete => hooks_core::ttACCOUNT_DELETE,
            TxType::SetHook => hooks_core::ttHOOK_SET,
            TxType::NFTokenMint => hooks_core::ttNFTOKEN_MINT,
            TxType::NFTokenBurn => hooks_core::ttNFTOKEN_BURN,
            TxType::NFTokenCreateOffer => hooks_core::ttNFTOKEN_CREATE_OFFER,
            TxType::NFTokenCancelOffer => hooks_core::ttNFTOKEN_CANCEL_OFFER,
            TxType::NFTokenAcceptOffer => hooks_core::ttNFTOKEN_ACCEPT_OFFER,
            TxType::Clawback => hooks_core::ttCLAWBACK,
            TxType::AMMClawback => hooks_core::ttAMM_CLAWBACK,
            TxType::AMMCreate => hooks_core::ttAMM_CREATE,
            TxType::AMMDeposit => hooks_core::ttAMM_DEPOSIT,
            TxType::AMMWithdraw => hooks_core::ttAMM_WITHDRAW,
            TxType::AMMVote => hooks_core::ttAMM_VOTE,
            TxType::AMMBid => hooks_core::ttAMM_BID,
            TxType::AMMDelete => hooks_core::ttAMM_DELETE,
            TxType::URITokenMint => hooks_core::ttURITOKEN_MINT,
            TxType::URITokenBurn => hooks_core::ttURITOKEN_BURN,
            TxType::URITokenBuy => hooks_core::ttURITOKEN_BUY,
            TxType::URITokenCreateSellOffer => hooks_core::ttURITOKEN_CREATE_SELL_OFFER,
            TxType::URITokenCancelSellOffer => hooks_core::ttURITOKEN_CANCEL_SELL_OFFER,
            TxType::XChainCreateClaimID => hooks_core::ttXCHAIN_CREATE_CLAIM_ID,
            TxType::XChainCommit => hooks_core::ttXCHAIN_COMMIT,
            TxType::XChainClaim => hooks_core::ttXCHAIN_CLAIM,
            TxType::XChainAccountCreateCommit => hooks_core::ttXCHAIN_ACCOUNT_CREATE_COMMIT,
            TxType::XChainAddClaimAttestation => hooks_core::ttXCHAIN_ADD_CLAIM_ATTESTATION,
            TxType::XChainAddAccountCreateAttestation => {
                hooks_core::ttXCHAIN_ADD_ACCOUNT_CREATE_ATTESTATION
            }
            TxType::XChainModifyBridge => hooks_core::ttXCHAIN_MODIFY_BRIDGE,
            TxType::XChainCreateBridge => hooks_core::ttXCHAIN_CREATE_BRIDGE,
            TxType::DIDSet => hooks_core::ttDID_SET,
            TxType::DIDDelete => hooks_core::ttDID_DELETE,
            TxType::OracleSet => hooks_core::ttORACLE_SET,
            TxType::OracleDelete => hooks_core::ttORACLE_DELETE,
            TxType::LedgerStateFix => hooks_core::ttLEDGER_STATE_FIX,
            TxType::MPTokenIssuanceCreate => hooks_core::ttMPTOKEN_ISSUANCE_CREATE,
            TxType::MPTokenIssuanceDestroy => hooks_core::ttMPTOKEN_ISSUANCE_DESTROY,
            TxType::MPTokenIssuanceSet => hooks_core::ttMPTOKEN_ISSUANCE_SET,
            TxType::MPTokenAuthorize => hooks_core::ttMPTOKEN_AUTHORIZE,
            TxType::CredentialCreate => hooks_core::ttCREDENTIAL_CREATE,
            TxType::CredentialAccept => hooks_core::ttCREDENTIAL_ACCEPT,
            TxType::CredentialDelete => hooks_core::ttCREDENTIAL_DELETE,
            TxType::NFTokenModify => hooks_core::ttNFTOKEN_MODIFY,
            TxType::PermissionedDomainSet => hooks_core::ttPERMISSIONED_DOMAIN_SET,
            TxType::PermissionedDomainDelete => hooks_core::ttPERMISSIONED_DOMAIN_DELETE,
            TxType::Cron => hooks_core::ttCRON,
            TxType::CronSet => hooks_core::ttCRON_SET,
            TxType::SetRemarks => hooks_core::ttREMARKS_SET,
            TxType::Remit => hooks_core::ttREMIT,
            TxType::GenesisMint => hooks_core::ttGENESIS_MINT,
            TxType::Import => hooks_core::ttIMPORT,
            TxType::ClaimReward => hooks_core::ttCLAIM_REWARD,
            TxType::Invoke => hooks_core::ttINVOKE,
            TxType::EnableAmendment => hooks_core::ttAMENDMENT,
            TxType::SetFee => hooks_core::ttFEE,
            TxType::UNLModify => hooks_core::ttUNL_MODIFY,
            TxType::EmitFailure => hooks_core::ttEMIT_FAILURE,
            TxType::UNLReport => hooks_core::ttUNL_REPORT,
            TxType::Unknown(code) => code,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips_known_codes() {
        let known: &[u16] = &[
            0, 1, 2, 3, 4, 5, 7, 8, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 25, 26, 27, 28,
            29, 30, 31, 35, 36, 37, 38, 39, 40, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
            58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 92, 93, 94, 95, 96, 97, 98,
            99, 100, 101, 102, 103, 104,
        ];
        for &code in known {
            assert_eq!(
                TxType::from(code).code(),
                code,
                "round-trip failed for {code}"
            );
        }
    }

    #[test]
    fn unknown_code_round_trips() {
        let ty = TxType::from(9999);
        assert_eq!(ty, TxType::Unknown(9999));
        assert_eq!(ty.code(), 9999);
    }
}
