// @generated by `cargo xtask gen-core` from crates/hooks-core/vendor/xahaud-hook/tts.h — DO NOT EDIT BY HAND.
//! Transaction type (`TxType`) model.
//!
//! [`TxType`] is a typed, exhaustive-by-construction mirror of the raw
//! `tt*` transaction-type codes in `hooks_core::tts` (plus
//! [`TxType::Unknown`] for forward-compatibility with codes this crate
//! does not yet know about) — the same pattern [`crate::error::HookError`]
//! uses for the Hook API's negative error-code channel, applied here to
//! [`crate::api::otxn::otxn_type`]'s `u16` transaction-type channel.

/// The transaction type of the originating transaction, decoded from the
/// raw `u16` `tt*` code returned by [`crate::api::otxn::otxn_type`].
///
/// # Examples
///
/// ```
/// use hooks_lib::tx_type::TxType;
///
/// let ty = TxType::from(5);
/// assert_eq!(ty, TxType::RegularKeySet);
/// assert_eq!(ty.code(), 5);
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TxType {
    /// `ttPAYMENT` (0).
    Payment,
    /// `ttESCROW_CREATE` (1).
    EscrowCreate,
    /// `ttESCROW_FINISH` (2).
    EscrowFinish,
    /// `ttACCOUNT_SET` (3).
    AccountSet,
    /// `ttESCROW_CANCEL` (4).
    EscrowCancel,
    /// `ttREGULAR_KEY_SET` (5).
    RegularKeySet,
    /// `ttOFFER_CREATE` (7).
    OfferCreate,
    /// `ttOFFER_CANCEL` (8).
    OfferCancel,
    /// `ttTICKET_CREATE` (10).
    TicketCreate,
    /// `ttSIGNER_LIST_SET` (12).
    SignerListSet,
    /// `ttPAYCHAN_CREATE` (13).
    PaychanCreate,
    /// `ttPAYCHAN_FUND` (14).
    PaychanFund,
    /// `ttPAYCHAN_CLAIM` (15).
    PaychanClaim,
    /// `ttCHECK_CREATE` (16).
    CheckCreate,
    /// `ttCHECK_CASH` (17).
    CheckCash,
    /// `ttCHECK_CANCEL` (18).
    CheckCancel,
    /// `ttDEPOSIT_PREAUTH` (19).
    DepositPreauth,
    /// `ttTRUST_SET` (20).
    TrustSet,
    /// `ttACCOUNT_DELETE` (21).
    AccountDelete,
    /// `ttHOOK_SET` (22).
    HookSet,
    /// `ttNFTOKEN_MINT` (25).
    NftokenMint,
    /// `ttNFTOKEN_BURN` (26).
    NftokenBurn,
    /// `ttNFTOKEN_CREATE_OFFER` (27).
    NftokenCreateOffer,
    /// `ttNFTOKEN_CANCEL_OFFER` (28).
    NftokenCancelOffer,
    /// `ttNFTOKEN_ACCEPT_OFFER` (29).
    NftokenAcceptOffer,
    /// `ttCLAWBACK` (30).
    Clawback,
    /// `ttAMM_CLAWBACK` (31).
    AmmClawback,
    /// `ttAMM_CREATE` (35).
    AmmCreate,
    /// `ttAMM_DEPOSIT` (36).
    AmmDeposit,
    /// `ttAMM_WITHDRAW` (37).
    AmmWithdraw,
    /// `ttAMM_VOTE` (38).
    AmmVote,
    /// `ttAMM_BID` (39).
    AmmBid,
    /// `ttAMM_DELETE` (40).
    AmmDelete,
    /// `ttURITOKEN_MINT` (45).
    UritokenMint,
    /// `ttURITOKEN_BURN` (46).
    UritokenBurn,
    /// `ttURITOKEN_BUY` (47).
    UritokenBuy,
    /// `ttURITOKEN_CREATE_SELL_OFFER` (48).
    UritokenCreateSellOffer,
    /// `ttURITOKEN_CANCEL_SELL_OFFER` (49).
    UritokenCancelSellOffer,
    /// `ttXCHAIN_CREATE_CLAIM_ID` (50).
    XchainCreateClaimId,
    /// `ttXCHAIN_COMMIT` (51).
    XchainCommit,
    /// `ttXCHAIN_CLAIM` (52).
    XchainClaim,
    /// `ttXCHAIN_ACCOUNT_CREATE_COMMIT` (53).
    XchainAccountCreateCommit,
    /// `ttXCHAIN_ADD_CLAIM_ATTESTATION` (54).
    XchainAddClaimAttestation,
    /// `ttXCHAIN_ADD_ACCOUNT_CREATE_ATTESTATION` (55).
    XchainAddAccountCreateAttestation,
    /// `ttXCHAIN_MODIFY_BRIDGE` (56).
    XchainModifyBridge,
    /// `ttXCHAIN_CREATE_BRIDGE` (57).
    XchainCreateBridge,
    /// `ttDID_SET` (58).
    DidSet,
    /// `ttDID_DELETE` (59).
    DidDelete,
    /// `ttORACLE_SET` (60).
    OracleSet,
    /// `ttORACLE_DELETE` (61).
    OracleDelete,
    /// `ttLEDGER_STATE_FIX` (62).
    LedgerStateFix,
    /// `ttMPTOKEN_ISSUANCE_CREATE` (63).
    MptokenIssuanceCreate,
    /// `ttMPTOKEN_ISSUANCE_DESTROY` (64).
    MptokenIssuanceDestroy,
    /// `ttMPTOKEN_ISSUANCE_SET` (65).
    MptokenIssuanceSet,
    /// `ttMPTOKEN_AUTHORIZE` (66).
    MptokenAuthorize,
    /// `ttCREDENTIAL_CREATE` (67).
    CredentialCreate,
    /// `ttCREDENTIAL_ACCEPT` (68).
    CredentialAccept,
    /// `ttCREDENTIAL_DELETE` (69).
    CredentialDelete,
    /// `ttNFTOKEN_MODIFY` (70).
    NftokenModify,
    /// `ttPERMISSIONED_DOMAIN_SET` (71).
    PermissionedDomainSet,
    /// `ttPERMISSIONED_DOMAIN_DELETE` (72).
    PermissionedDomainDelete,
    /// `ttCRON` (92).
    Cron,
    /// `ttCRON_SET` (93).
    CronSet,
    /// `ttREMARKS_SET` (94).
    RemarksSet,
    /// `ttREMIT` (95).
    Remit,
    /// `ttGENESIS_MINT` (96).
    GenesisMint,
    /// `ttIMPORT` (97).
    Import,
    /// `ttCLAIM_REWARD` (98).
    ClaimReward,
    /// `ttINVOKE` (99).
    Invoke,
    /// `ttAMENDMENT` (100).
    Amendment,
    /// `ttFEE` (101).
    Fee,
    /// `ttUNL_MODIFY` (102).
    UnlModify,
    /// `ttEMIT_FAILURE` (103).
    EmitFailure,
    /// `ttUNL_REPORT` (104).
    UnlReport,

    /// A code this version of hooks-lib does not recognize yet. Carries
    /// the raw code for forward-compatibility.
    Unknown(u16),
}

impl From<u16> for TxType {
    fn from(code: u16) -> Self {
        match code {
            hooks_core::ttPAYMENT => TxType::Payment,
            hooks_core::ttESCROW_CREATE => TxType::EscrowCreate,
            hooks_core::ttESCROW_FINISH => TxType::EscrowFinish,
            hooks_core::ttACCOUNT_SET => TxType::AccountSet,
            hooks_core::ttESCROW_CANCEL => TxType::EscrowCancel,
            hooks_core::ttREGULAR_KEY_SET => TxType::RegularKeySet,
            hooks_core::ttOFFER_CREATE => TxType::OfferCreate,
            hooks_core::ttOFFER_CANCEL => TxType::OfferCancel,
            hooks_core::ttTICKET_CREATE => TxType::TicketCreate,
            hooks_core::ttSIGNER_LIST_SET => TxType::SignerListSet,
            hooks_core::ttPAYCHAN_CREATE => TxType::PaychanCreate,
            hooks_core::ttPAYCHAN_FUND => TxType::PaychanFund,
            hooks_core::ttPAYCHAN_CLAIM => TxType::PaychanClaim,
            hooks_core::ttCHECK_CREATE => TxType::CheckCreate,
            hooks_core::ttCHECK_CASH => TxType::CheckCash,
            hooks_core::ttCHECK_CANCEL => TxType::CheckCancel,
            hooks_core::ttDEPOSIT_PREAUTH => TxType::DepositPreauth,
            hooks_core::ttTRUST_SET => TxType::TrustSet,
            hooks_core::ttACCOUNT_DELETE => TxType::AccountDelete,
            hooks_core::ttHOOK_SET => TxType::HookSet,
            hooks_core::ttNFTOKEN_MINT => TxType::NftokenMint,
            hooks_core::ttNFTOKEN_BURN => TxType::NftokenBurn,
            hooks_core::ttNFTOKEN_CREATE_OFFER => TxType::NftokenCreateOffer,
            hooks_core::ttNFTOKEN_CANCEL_OFFER => TxType::NftokenCancelOffer,
            hooks_core::ttNFTOKEN_ACCEPT_OFFER => TxType::NftokenAcceptOffer,
            hooks_core::ttCLAWBACK => TxType::Clawback,
            hooks_core::ttAMM_CLAWBACK => TxType::AmmClawback,
            hooks_core::ttAMM_CREATE => TxType::AmmCreate,
            hooks_core::ttAMM_DEPOSIT => TxType::AmmDeposit,
            hooks_core::ttAMM_WITHDRAW => TxType::AmmWithdraw,
            hooks_core::ttAMM_VOTE => TxType::AmmVote,
            hooks_core::ttAMM_BID => TxType::AmmBid,
            hooks_core::ttAMM_DELETE => TxType::AmmDelete,
            hooks_core::ttURITOKEN_MINT => TxType::UritokenMint,
            hooks_core::ttURITOKEN_BURN => TxType::UritokenBurn,
            hooks_core::ttURITOKEN_BUY => TxType::UritokenBuy,
            hooks_core::ttURITOKEN_CREATE_SELL_OFFER => TxType::UritokenCreateSellOffer,
            hooks_core::ttURITOKEN_CANCEL_SELL_OFFER => TxType::UritokenCancelSellOffer,
            hooks_core::ttXCHAIN_CREATE_CLAIM_ID => TxType::XchainCreateClaimId,
            hooks_core::ttXCHAIN_COMMIT => TxType::XchainCommit,
            hooks_core::ttXCHAIN_CLAIM => TxType::XchainClaim,
            hooks_core::ttXCHAIN_ACCOUNT_CREATE_COMMIT => TxType::XchainAccountCreateCommit,
            hooks_core::ttXCHAIN_ADD_CLAIM_ATTESTATION => TxType::XchainAddClaimAttestation,
            hooks_core::ttXCHAIN_ADD_ACCOUNT_CREATE_ATTESTATION => {
                TxType::XchainAddAccountCreateAttestation
            }
            hooks_core::ttXCHAIN_MODIFY_BRIDGE => TxType::XchainModifyBridge,
            hooks_core::ttXCHAIN_CREATE_BRIDGE => TxType::XchainCreateBridge,
            hooks_core::ttDID_SET => TxType::DidSet,
            hooks_core::ttDID_DELETE => TxType::DidDelete,
            hooks_core::ttORACLE_SET => TxType::OracleSet,
            hooks_core::ttORACLE_DELETE => TxType::OracleDelete,
            hooks_core::ttLEDGER_STATE_FIX => TxType::LedgerStateFix,
            hooks_core::ttMPTOKEN_ISSUANCE_CREATE => TxType::MptokenIssuanceCreate,
            hooks_core::ttMPTOKEN_ISSUANCE_DESTROY => TxType::MptokenIssuanceDestroy,
            hooks_core::ttMPTOKEN_ISSUANCE_SET => TxType::MptokenIssuanceSet,
            hooks_core::ttMPTOKEN_AUTHORIZE => TxType::MptokenAuthorize,
            hooks_core::ttCREDENTIAL_CREATE => TxType::CredentialCreate,
            hooks_core::ttCREDENTIAL_ACCEPT => TxType::CredentialAccept,
            hooks_core::ttCREDENTIAL_DELETE => TxType::CredentialDelete,
            hooks_core::ttNFTOKEN_MODIFY => TxType::NftokenModify,
            hooks_core::ttPERMISSIONED_DOMAIN_SET => TxType::PermissionedDomainSet,
            hooks_core::ttPERMISSIONED_DOMAIN_DELETE => TxType::PermissionedDomainDelete,
            hooks_core::ttCRON => TxType::Cron,
            hooks_core::ttCRON_SET => TxType::CronSet,
            hooks_core::ttREMARKS_SET => TxType::RemarksSet,
            hooks_core::ttREMIT => TxType::Remit,
            hooks_core::ttGENESIS_MINT => TxType::GenesisMint,
            hooks_core::ttIMPORT => TxType::Import,
            hooks_core::ttCLAIM_REWARD => TxType::ClaimReward,
            hooks_core::ttINVOKE => TxType::Invoke,
            hooks_core::ttAMENDMENT => TxType::Amendment,
            hooks_core::ttFEE => TxType::Fee,
            hooks_core::ttUNL_MODIFY => TxType::UnlModify,
            hooks_core::ttEMIT_FAILURE => TxType::EmitFailure,
            hooks_core::ttUNL_REPORT => TxType::UnlReport,
            other => TxType::Unknown(other),
        }
    }
}

impl TxType {
    /// The raw `u16` code this variant corresponds to. Exact inverse of
    /// [`TxType::from`]: `TxType::from(c).code() == c` for every code,
    /// known or unknown.
    #[inline(always)]
    #[must_use]
    pub fn code(&self) -> u16 {
        match *self {
            TxType::Payment => hooks_core::ttPAYMENT,
            TxType::EscrowCreate => hooks_core::ttESCROW_CREATE,
            TxType::EscrowFinish => hooks_core::ttESCROW_FINISH,
            TxType::AccountSet => hooks_core::ttACCOUNT_SET,
            TxType::EscrowCancel => hooks_core::ttESCROW_CANCEL,
            TxType::RegularKeySet => hooks_core::ttREGULAR_KEY_SET,
            TxType::OfferCreate => hooks_core::ttOFFER_CREATE,
            TxType::OfferCancel => hooks_core::ttOFFER_CANCEL,
            TxType::TicketCreate => hooks_core::ttTICKET_CREATE,
            TxType::SignerListSet => hooks_core::ttSIGNER_LIST_SET,
            TxType::PaychanCreate => hooks_core::ttPAYCHAN_CREATE,
            TxType::PaychanFund => hooks_core::ttPAYCHAN_FUND,
            TxType::PaychanClaim => hooks_core::ttPAYCHAN_CLAIM,
            TxType::CheckCreate => hooks_core::ttCHECK_CREATE,
            TxType::CheckCash => hooks_core::ttCHECK_CASH,
            TxType::CheckCancel => hooks_core::ttCHECK_CANCEL,
            TxType::DepositPreauth => hooks_core::ttDEPOSIT_PREAUTH,
            TxType::TrustSet => hooks_core::ttTRUST_SET,
            TxType::AccountDelete => hooks_core::ttACCOUNT_DELETE,
            TxType::HookSet => hooks_core::ttHOOK_SET,
            TxType::NftokenMint => hooks_core::ttNFTOKEN_MINT,
            TxType::NftokenBurn => hooks_core::ttNFTOKEN_BURN,
            TxType::NftokenCreateOffer => hooks_core::ttNFTOKEN_CREATE_OFFER,
            TxType::NftokenCancelOffer => hooks_core::ttNFTOKEN_CANCEL_OFFER,
            TxType::NftokenAcceptOffer => hooks_core::ttNFTOKEN_ACCEPT_OFFER,
            TxType::Clawback => hooks_core::ttCLAWBACK,
            TxType::AmmClawback => hooks_core::ttAMM_CLAWBACK,
            TxType::AmmCreate => hooks_core::ttAMM_CREATE,
            TxType::AmmDeposit => hooks_core::ttAMM_DEPOSIT,
            TxType::AmmWithdraw => hooks_core::ttAMM_WITHDRAW,
            TxType::AmmVote => hooks_core::ttAMM_VOTE,
            TxType::AmmBid => hooks_core::ttAMM_BID,
            TxType::AmmDelete => hooks_core::ttAMM_DELETE,
            TxType::UritokenMint => hooks_core::ttURITOKEN_MINT,
            TxType::UritokenBurn => hooks_core::ttURITOKEN_BURN,
            TxType::UritokenBuy => hooks_core::ttURITOKEN_BUY,
            TxType::UritokenCreateSellOffer => hooks_core::ttURITOKEN_CREATE_SELL_OFFER,
            TxType::UritokenCancelSellOffer => hooks_core::ttURITOKEN_CANCEL_SELL_OFFER,
            TxType::XchainCreateClaimId => hooks_core::ttXCHAIN_CREATE_CLAIM_ID,
            TxType::XchainCommit => hooks_core::ttXCHAIN_COMMIT,
            TxType::XchainClaim => hooks_core::ttXCHAIN_CLAIM,
            TxType::XchainAccountCreateCommit => hooks_core::ttXCHAIN_ACCOUNT_CREATE_COMMIT,
            TxType::XchainAddClaimAttestation => hooks_core::ttXCHAIN_ADD_CLAIM_ATTESTATION,
            TxType::XchainAddAccountCreateAttestation => {
                hooks_core::ttXCHAIN_ADD_ACCOUNT_CREATE_ATTESTATION
            }
            TxType::XchainModifyBridge => hooks_core::ttXCHAIN_MODIFY_BRIDGE,
            TxType::XchainCreateBridge => hooks_core::ttXCHAIN_CREATE_BRIDGE,
            TxType::DidSet => hooks_core::ttDID_SET,
            TxType::DidDelete => hooks_core::ttDID_DELETE,
            TxType::OracleSet => hooks_core::ttORACLE_SET,
            TxType::OracleDelete => hooks_core::ttORACLE_DELETE,
            TxType::LedgerStateFix => hooks_core::ttLEDGER_STATE_FIX,
            TxType::MptokenIssuanceCreate => hooks_core::ttMPTOKEN_ISSUANCE_CREATE,
            TxType::MptokenIssuanceDestroy => hooks_core::ttMPTOKEN_ISSUANCE_DESTROY,
            TxType::MptokenIssuanceSet => hooks_core::ttMPTOKEN_ISSUANCE_SET,
            TxType::MptokenAuthorize => hooks_core::ttMPTOKEN_AUTHORIZE,
            TxType::CredentialCreate => hooks_core::ttCREDENTIAL_CREATE,
            TxType::CredentialAccept => hooks_core::ttCREDENTIAL_ACCEPT,
            TxType::CredentialDelete => hooks_core::ttCREDENTIAL_DELETE,
            TxType::NftokenModify => hooks_core::ttNFTOKEN_MODIFY,
            TxType::PermissionedDomainSet => hooks_core::ttPERMISSIONED_DOMAIN_SET,
            TxType::PermissionedDomainDelete => hooks_core::ttPERMISSIONED_DOMAIN_DELETE,
            TxType::Cron => hooks_core::ttCRON,
            TxType::CronSet => hooks_core::ttCRON_SET,
            TxType::RemarksSet => hooks_core::ttREMARKS_SET,
            TxType::Remit => hooks_core::ttREMIT,
            TxType::GenesisMint => hooks_core::ttGENESIS_MINT,
            TxType::Import => hooks_core::ttIMPORT,
            TxType::ClaimReward => hooks_core::ttCLAIM_REWARD,
            TxType::Invoke => hooks_core::ttINVOKE,
            TxType::Amendment => hooks_core::ttAMENDMENT,
            TxType::Fee => hooks_core::ttFEE,
            TxType::UnlModify => hooks_core::ttUNL_MODIFY,
            TxType::EmitFailure => hooks_core::ttEMIT_FAILURE,
            TxType::UnlReport => hooks_core::ttUNL_REPORT,
            TxType::Unknown(code) => code,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips_known_codes() {
        let known: &[u16] = &[
            0, 1, 2, 3, 4, 5, 7, 8, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 25, 26, 27, 28,
            29, 30, 31, 35, 36, 37, 38, 39, 40, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
            58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 92, 93, 94, 95, 96, 97, 98,
            99, 100, 101, 102, 103, 104,
        ];
        for &code in known {
            assert_eq!(
                TxType::from(code).code(),
                code,
                "round-trip failed for {code}"
            );
        }
    }

    #[test]
    fn unknown_code_round_trips() {
        let ty = TxType::from(9999);
        assert_eq!(ty, TxType::Unknown(9999));
        assert_eq!(ty.code(), 9999);
    }
}
