// @generated by `cargo xtask gen-core` from crates/rshooks-core/vendor/xahaud-hook/error.h — DO NOT EDIT BY HAND.
//! Hook API error codes.
//!
//! Upstream: `Xahau/xahaud`, branch `release`, `hook/error.h`, vendored at
//! `crates/rshooks-core/vendor/xahaud-hook/error.h`.
//!
//! Every Hook API function returns an `i64`; non-negative values are
//! success payloads (often "bytes written"), negative values are one of
//! the error codes below. Kept verbatim (name and value) from the C header.

/// C: `SUCCESS` (error.h)
pub const SUCCESS: i64 = 0;
/// C: `OUT_OF_BOUNDS` (error.h)
pub const OUT_OF_BOUNDS: i64 = -1;
/// C: `INTERNAL_ERROR` (error.h)
pub const INTERNAL_ERROR: i64 = -2;
/// C: `TOO_BIG` (error.h)
pub const TOO_BIG: i64 = -3;
/// C: `TOO_SMALL` (error.h)
pub const TOO_SMALL: i64 = -4;
/// C: `DOESNT_EXIST` (error.h)
pub const DOESNT_EXIST: i64 = -5;
/// C: `NO_FREE_SLOTS` (error.h)
pub const NO_FREE_SLOTS: i64 = -6;
/// C: `INVALID_ARGUMENT` (error.h)
pub const INVALID_ARGUMENT: i64 = -7;
/// C: `ALREADY_SET` (error.h)
pub const ALREADY_SET: i64 = -8;
/// C: `PREREQUISITE_NOT_MET` (error.h)
pub const PREREQUISITE_NOT_MET: i64 = -9;
/// C: `FEE_TOO_LARGE` (error.h)
pub const FEE_TOO_LARGE: i64 = -10;
/// C: `EMISSION_FAILURE` (error.h)
pub const EMISSION_FAILURE: i64 = -11;
/// C: `TOO_MANY_NONCES` (error.h)
pub const TOO_MANY_NONCES: i64 = -12;
/// C: `TOO_MANY_EMITTED_TXN` (error.h)
pub const TOO_MANY_EMITTED_TXN: i64 = -13;
/// C: `NOT_IMPLEMENTED` (error.h)
pub const NOT_IMPLEMENTED: i64 = -14;
/// C: `INVALID_ACCOUNT` (error.h)
pub const INVALID_ACCOUNT: i64 = -15;
/// C: `GUARD_VIOLATION` (error.h)
pub const GUARD_VIOLATION: i64 = -16;
/// C: `INVALID_FIELD` (error.h)
pub const INVALID_FIELD: i64 = -17;
/// C: `PARSE_ERROR` (error.h)
pub const PARSE_ERROR: i64 = -18;
/// C: `RC_ROLLBACK` (error.h)
pub const RC_ROLLBACK: i64 = -19;
/// C: `RC_ACCEPT` (error.h)
pub const RC_ACCEPT: i64 = -20;
/// C: `NO_SUCH_KEYLET` (error.h)
pub const NO_SUCH_KEYLET: i64 = -21;
/// C: `NOT_AN_ARRAY` (error.h)
pub const NOT_AN_ARRAY: i64 = -22;
/// C: `NOT_AN_OBJECT` (error.h)
pub const NOT_AN_OBJECT: i64 = -23;
/// C: `INVALID_FLOAT` (error.h) — note the upstream value is `-10024`, not
/// `-24` (kept verbatim; this is not a typo in this translation).
pub const INVALID_FLOAT: i64 = -10024;
/// C: `DIVISION_BY_ZERO` (error.h)
pub const DIVISION_BY_ZERO: i64 = -25;
/// C: `MANTISSA_OVERSIZED` (error.h)
pub const MANTISSA_OVERSIZED: i64 = -26;
/// C: `MANTISSA_UNDERSIZED` (error.h)
pub const MANTISSA_UNDERSIZED: i64 = -27;
/// C: `EXPONENT_OVERSIZED` (error.h)
pub const EXPONENT_OVERSIZED: i64 = -28;
/// C: `EXPONENT_UNDERSIZED` (error.h)
pub const EXPONENT_UNDERSIZED: i64 = -29;
/// C: `XFL_OVERFLOW` (error.h)
pub const XFL_OVERFLOW: i64 = -30;
/// C: `NOT_IOU_AMOUNT` (error.h)
pub const NOT_IOU_AMOUNT: i64 = -31;
/// C: `NOT_AN_AMOUNT` (error.h)
pub const NOT_AN_AMOUNT: i64 = -32;
/// C: `CANT_RETURN_NEGATIVE` (error.h)
pub const CANT_RETURN_NEGATIVE: i64 = -33;
/// C: `NOT_AUTHORIZED` (error.h)
pub const NOT_AUTHORIZED: i64 = -34;
/// C: `PREVIOUS_FAILURE_PREVENTS_RETRY` (error.h)
pub const PREVIOUS_FAILURE_PREVENTS_RETRY: i64 = -35;
/// C: `TOO_MANY_PARAMS` (error.h)
pub const TOO_MANY_PARAMS: i64 = -36;
/// C: `INVALID_TXN` (error.h)
pub const INVALID_TXN: i64 = -37;
/// C: `RESERVE_INSUFFICIENT` (error.h)
pub const RESERVE_INSUFFICIENT: i64 = -38;
/// C: `COMPLEX_NOT_SUPPORTED` (error.h)
pub const COMPLEX_NOT_SUPPORTED: i64 = -39;
/// C: `DOES_NOT_MATCH` (error.h)
pub const DOES_NOT_MATCH: i64 = -40;
/// C: `INVALID_KEY` (error.h)
pub const INVALID_KEY: i64 = -41;
/// C: `NOT_A_STRING` (error.h)
pub const NOT_A_STRING: i64 = -42;
/// C: `MEM_OVERLAP` (error.h)
pub const MEM_OVERLAP: i64 = -43;
/// C: `TOO_MANY_STATE_MODIFICATIONS` (error.h)
pub const TOO_MANY_STATE_MODIFICATIONS: i64 = -44;
/// C: `TOO_MANY_NAMESPACES` (error.h)
pub const TOO_MANY_NAMESPACES: i64 = -45;
