// @generated by `cargo xtask gen-core` from crates/rshooks-core/vendor/xahaud-hook/ls_flags.h — DO NOT EDIT BY HAND.
//! Ledger entry flags (`lsfXxx`).
//!
//! Upstream: `Xahau/xahaud`, branch `release`, `hook/ls_flags.h`, vendored at
//! `crates/rshooks-core/vendor/xahaud-hook/ls_flags.h`.
//!
//! The header groups these into several unnamed-in-Rust C enums, one per
//! ledger entry type (`ltACCOUNT_ROOT`, `ltOFFER`, ...). This translation
//! flattens every enum into a single list of `pub const`s, in header order;
//! no name collides across enums (verified against the header), so every
//! name is kept verbatim with no disambiguation prefix.

// enum ltACCOUNT_ROOT
/// C: `lsfPasswordSpent` (ls_flags.h, `enum ltACCOUNT_ROOT`)
pub const lsfPasswordSpent: u32 = 0x0001_0000;
/// C: `lsfRequireDestTag` (ls_flags.h, `enum ltACCOUNT_ROOT`)
pub const lsfRequireDestTag: u32 = 0x0002_0000;
/// C: `lsfRequireAuth` (ls_flags.h, `enum ltACCOUNT_ROOT`)
pub const lsfRequireAuth: u32 = 0x0004_0000;
/// C: `lsfDisallowXRP` (ls_flags.h, `enum ltACCOUNT_ROOT`)
pub const lsfDisallowXRP: u32 = 0x0008_0000;
/// C: `lsfDisableMaster` (ls_flags.h, `enum ltACCOUNT_ROOT`)
pub const lsfDisableMaster: u32 = 0x0010_0000;
/// C: `lsfNoFreeze` (ls_flags.h, `enum ltACCOUNT_ROOT`)
pub const lsfNoFreeze: u32 = 0x0020_0000;
/// C: `lsfGlobalFreeze` (ls_flags.h, `enum ltACCOUNT_ROOT`)
pub const lsfGlobalFreeze: u32 = 0x0040_0000;
/// C: `lsfDefaultRipple` (ls_flags.h, `enum ltACCOUNT_ROOT`)
pub const lsfDefaultRipple: u32 = 0x0080_0000;
/// C: `lsfDepositAuth` (ls_flags.h, `enum ltACCOUNT_ROOT`)
pub const lsfDepositAuth: u32 = 0x0100_0000;
/// C: `lsfTshCollect` (ls_flags.h, `enum ltACCOUNT_ROOT`)
pub const lsfTshCollect: u32 = 0x0200_0000;
/// C: `lsfDisallowIncomingNFTokenOffer` (ls_flags.h, `enum ltACCOUNT_ROOT`)
pub const lsfDisallowIncomingNFTokenOffer: u32 = 0x0400_0000;
/// C: `lsfDisallowIncomingCheck` (ls_flags.h, `enum ltACCOUNT_ROOT`)
pub const lsfDisallowIncomingCheck: u32 = 0x0800_0000;
/// C: `lsfDisallowIncomingPayChan` (ls_flags.h, `enum ltACCOUNT_ROOT`)
pub const lsfDisallowIncomingPayChan: u32 = 0x1000_0000;
/// C: `lsfDisallowIncomingTrustline` (ls_flags.h, `enum ltACCOUNT_ROOT`)
pub const lsfDisallowIncomingTrustline: u32 = 0x2000_0000;
/// C: `lsfURITokenIssuer` (ls_flags.h, `enum ltACCOUNT_ROOT`)
pub const lsfURITokenIssuer: u32 = 0x4000_0000;
/// C: `lsfDisallowIncomingRemit` (ls_flags.h, `enum ltACCOUNT_ROOT`)
pub const lsfDisallowIncomingRemit: u32 = 0x8000_0000;
/// C: `lsfAllowTrustLineClawback` (ls_flags.h, `enum ltACCOUNT_ROOT`)
pub const lsfAllowTrustLineClawback: u32 = 0x0000_1000;

// enum ltOFFER
/// C: `lsfPassive` (ls_flags.h, `enum ltOFFER`)
pub const lsfPassive: u32 = 0x0001_0000;
/// C: `lsfSell` (ls_flags.h, `enum ltOFFER`)
pub const lsfSell: u32 = 0x0002_0000;

// enum ltRIPPLE_STATE
/// C: `lsfLowReserve` (ls_flags.h, `enum ltRIPPLE_STATE`)
pub const lsfLowReserve: u32 = 0x0001_0000;
/// C: `lsfHighReserve` (ls_flags.h, `enum ltRIPPLE_STATE`)
pub const lsfHighReserve: u32 = 0x0002_0000;
/// C: `lsfLowAuth` (ls_flags.h, `enum ltRIPPLE_STATE`)
pub const lsfLowAuth: u32 = 0x0004_0000;
/// C: `lsfHighAuth` (ls_flags.h, `enum ltRIPPLE_STATE`)
pub const lsfHighAuth: u32 = 0x0008_0000;
/// C: `lsfLowNoRipple` (ls_flags.h, `enum ltRIPPLE_STATE`)
pub const lsfLowNoRipple: u32 = 0x0010_0000;
/// C: `lsfHighNoRipple` (ls_flags.h, `enum ltRIPPLE_STATE`)
pub const lsfHighNoRipple: u32 = 0x0020_0000;
/// C: `lsfLowFreeze` (ls_flags.h, `enum ltRIPPLE_STATE`)
pub const lsfLowFreeze: u32 = 0x0040_0000;
/// C: `lsfHighFreeze` (ls_flags.h, `enum ltRIPPLE_STATE`)
pub const lsfHighFreeze: u32 = 0x0080_0000;
/// C: `lsfLowDeepFreeze` (ls_flags.h, `enum ltRIPPLE_STATE`)
pub const lsfLowDeepFreeze: u32 = 0x0200_0000;
/// C: `lsfHighDeepFreeze` (ls_flags.h, `enum ltRIPPLE_STATE`)
pub const lsfHighDeepFreeze: u32 = 0x0400_0000;
/// C: `lsfAMMNode` (ls_flags.h, `enum ltRIPPLE_STATE`)
pub const lsfAMMNode: u32 = 0x0100_0000;

// enum ltSIGNER_LIST
/// C: `lsfOneOwnerCount` (ls_flags.h, `enum ltSIGNER_LIST`)
pub const lsfOneOwnerCount: u32 = 0x0001_0000;

// enum ltDIR_NODE
/// C: `lsfNFTokenBuyOffers` (ls_flags.h, `enum ltDIR_NODE`)
pub const lsfNFTokenBuyOffers: u32 = 0x0000_0001;
/// C: `lsfNFTokenSellOffers` (ls_flags.h, `enum ltDIR_NODE`)
pub const lsfNFTokenSellOffers: u32 = 0x0000_0002;
/// C: `lsfEmittedDir` (ls_flags.h, `enum ltDIR_NODE`)
pub const lsfEmittedDir: u32 = 0x0000_0004;

// enum ltNFTOKEN_OFFER
/// C: `lsfSellNFToken` (ls_flags.h, `enum ltNFTOKEN_OFFER`)
pub const lsfSellNFToken: u32 = 0x0000_0001;

// enum ltURI_TOKEN
/// C: `lsfBurnable` (ls_flags.h, `enum ltURI_TOKEN`)
pub const lsfBurnable: u32 = 0x0000_0001;

// enum remarks
/// C: `lsfImmutable` (ls_flags.h, `enum remarks`)
pub const lsfImmutable: u32 = 1;

// enum ltMPTOKEN_ISSUANCE
/// C: `lsfMPTLocked` (ls_flags.h, `enum ltMPTOKEN_ISSUANCE`)
pub const lsfMPTLocked: u32 = 0x0000_0001;
/// C: `lsfMPTCanLock` (ls_flags.h, `enum ltMPTOKEN_ISSUANCE`)
pub const lsfMPTCanLock: u32 = 0x0000_0002;
/// C: `lsfMPTRequireAuth` (ls_flags.h, `enum ltMPTOKEN_ISSUANCE`)
pub const lsfMPTRequireAuth: u32 = 0x0000_0004;
/// C: `lsfMPTCanEscrow` (ls_flags.h, `enum ltMPTOKEN_ISSUANCE`)
pub const lsfMPTCanEscrow: u32 = 0x0000_0008;
/// C: `lsfMPTCanTrade` (ls_flags.h, `enum ltMPTOKEN_ISSUANCE`)
pub const lsfMPTCanTrade: u32 = 0x0000_0010;
/// C: `lsfMPTCanTransfer` (ls_flags.h, `enum ltMPTOKEN_ISSUANCE`)
pub const lsfMPTCanTransfer: u32 = 0x0000_0020;
/// C: `lsfMPTCanClawback` (ls_flags.h, `enum ltMPTOKEN_ISSUANCE`)
pub const lsfMPTCanClawback: u32 = 0x0000_0040;

// enum ltMPTOKEN
/// C: `lsfMPTAuthorized` (ls_flags.h, `enum ltMPTOKEN`)
pub const lsfMPTAuthorized: u32 = 0x0000_0002;

// enum ltCREDENTIAL
/// C: `lsfAccepted` (ls_flags.h, `enum ltCREDENTIAL`)
pub const lsfAccepted: u32 = 0x0001_0000;
